CREATE DATABASE loadaDB;

USE loadaDB;

CREATE TABLE COMPANIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BANK_NAME VARCHAR(255) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    BRANCH_CODE VARCHAR(255) NOT NULL,
    TRACKER_LINK VARCHAR(255) NOT NULL
);

CREATE TABLE TRUCKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID INT NOT NULL,
    REGISTRATION_NUMBER VARCHAR(255) NOT NULL,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID)
);